<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Opportunity;
use Illuminate\Support\Facades\Hash;

class StartupSeeder extends Seeder
{
    public function run(): void
    {
        // 5 categories (sectors) with 3 startups each = 15 total
        $startups = [
            // ── FinTech (3) ──────────────────────────────────────────────
            [
                'title'            => 'PayEase BD',
                'sector'           => 'FinTech',
                'stage'            => 'Seed',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => 'Over 60% of Bangladeshi SMEs cannot accept digital payments due to high setup costs and complex onboarding processes, forcing them to rely on cash-only transactions.',
                'solution'         => 'PayEase BD provides a zero-setup-cost digital payment infrastructure for SMEs. Merchants can start accepting payments via QR code, mobile banking, and card within 24 hours.',
                'target_market'    => 'Bangladesh has 7.8 million SMEs. We target the 4.5 million urban and semi-urban businesses currently underserved by traditional payment processors.',
                'traction'         => 'Processing ৳2 crore/month across 1,200 merchants. MoM growth of 28%. Partnerships with 3 major mobile banking providers.',
                'ask_amount'       => 5000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Product development (40%), Sales & marketing (35%), Operations & compliance (25%)',
                'key_metrics'      => "Monthly GMV: ৳2 crore\nActive merchants: 1,200\nMoM growth: 28%\nTransaction success rate: 99.2%",
                'is_featured'      => true,
                'is_hot_deal'      => true,
            ],
            [
                'title'            => 'CreditBridge',
                'sector'           => 'FinTech',
                'stage'            => 'Pre-Seed',
                'location'         => 'Chittagong',
                'country'          => 'Bangladesh',
                'business_problem' => '65% of Bangladeshis lack formal credit history, making them ineligible for bank loans despite being creditworthy based on their actual financial behavior.',
                'solution'         => 'CreditBridge uses alternative data — mobile usage patterns, utility payments, and merchant transaction history — to generate credit scores for the unbanked population.',
                'target_market'    => 'Targeting 40 million unbanked adults in Bangladesh who need access to formal credit for business and personal needs.',
                'traction'         => 'Pilot with 500 users. 78% approval rate for loans facilitated. Partnership with 2 MFIs for loan disbursement.',
                'ask_amount'       => 3000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'AI model development (50%), Regulatory compliance (30%), Team expansion (20%)',
                'key_metrics'      => "Pilot users: 500\nLoan approval rate: 78%\nAverage loan size: ৳25,000\nDefault rate: 2.1%",
                'is_featured'      => false,
                'is_hot_deal'      => false,
            ],
            [
                'title'            => 'RemitFast',
                'sector'           => 'FinTech',
                'stage'            => 'Series A',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => 'Bangladesh receives $21B in annual remittances, but traditional channels charge 5-8% fees and take 2-5 days. This costs the diaspora over $1B annually in unnecessary fees.',
                'solution'         => 'RemitFast uses blockchain rails to enable near-instant remittances at under 1% fee. Recipients receive funds directly to mobile wallets within minutes.',
                'target_market'    => '10 million Bangladeshi diaspora sending money home. Primary corridors: UAE, Saudi Arabia, UK, USA, Malaysia.',
                'traction'         => '৳15 crore processed in last 6 months. 8,500 active users. Average transfer time: 4 minutes.',
                'ask_amount'       => 20000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Regulatory licenses in 5 countries (45%), Technology infrastructure (35%), Marketing (20%)',
                'key_metrics'      => "Monthly volume: ৳2.5 crore\nActive users: 8,500\nAvg transfer time: 4 min\nFee: 0.8%",
                'is_featured'      => true,
                'is_hot_deal'      => false,
            ],

            // ── AgriTech (3) ─────────────────────────────────────────────
            [
                'title'            => 'GreenHarvest',
                'sector'           => 'AgriTech',
                'stage'            => 'Seed',
                'location'         => 'Mymensingh',
                'country'          => 'Bangladesh',
                'business_problem' => 'Smallholder farmers in Bangladesh lose 30-40% of crops due to poor irrigation timing, over-fertilization, and lack of real-time field data.',
                'solution'         => 'GreenHarvest deploys IoT sensors and AI-driven analytics to help farmers optimize irrigation, fertilization, and harvest timing via a simple mobile app.',
                'target_market'    => '16 million smallholder farming households in Bangladesh. Initial focus on rice and vegetable farmers in Mymensingh and Rajshahi divisions.',
                'traction'         => 'Deployed across 1,200 farms. Average yield increase of 23%. Revenue: ৳18 lakh/month from subscription fees.',
                'ask_amount'       => 8000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Hardware manufacturing (40%), Geographic expansion (35%), R&D (25%)',
                'key_metrics'      => "Farms deployed: 1,200\nAvg yield increase: 23%\nMonthly revenue: ৳18 lakh\nChurn rate: 4%",
                'is_featured'      => true,
                'is_hot_deal'      => true,
            ],
            [
                'title'            => 'AgriLend',
                'sector'           => 'AgriTech',
                'stage'            => 'Pre-Seed',
                'location'         => 'Rajshahi',
                'country'          => 'Bangladesh',
                'business_problem' => 'Farmers need credit before planting season but repayment cycles don\'t match harvest timelines, leading to defaults and exclusion from formal credit.',
                'solution'         => 'AgriLend provides harvest-cycle-linked micro-loans to farmers. Repayment is automatically scheduled after harvest, reducing default risk for both parties.',
                'target_market'    => '5 million farming households needing seasonal credit. Partnering with cooperatives and NGOs for distribution.',
                'traction'         => '300 loans disbursed totaling ৳45 lakh. Default rate: 1.8%. NPS score: 72.',
                'ask_amount'       => 4000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Loan capital (60%), Technology platform (25%), Operations (15%)',
                'key_metrics'      => "Loans disbursed: 300\nTotal portfolio: ৳45 lakh\nDefault rate: 1.8%\nNPS: 72",
                'is_featured'      => false,
                'is_hot_deal'      => false,
            ],
            [
                'title'            => 'FreshChain',
                'sector'           => 'AgriTech',
                'stage'            => 'Seed',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => '40% of fresh produce in Bangladesh is wasted due to poor cold chain infrastructure, costing farmers and consumers billions annually.',
                'solution'         => 'FreshChain operates a network of solar-powered cold storage hubs in rural areas, connected to urban markets via a logistics platform.',
                'target_market'    => 'Vegetable and fruit farmers within 50km of major cities. Initial focus on Dhaka-Mymensingh corridor.',
                'traction'         => '3 cold hubs operational. 450 farmer partners. ৳12 lakh monthly revenue. Waste reduction: 65% for partner farmers.',
                'ask_amount'       => 15000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Cold hub expansion (55%), Logistics fleet (30%), Technology (15%)',
                'key_metrics'      => "Cold hubs: 3\nFarmer partners: 450\nMonthly revenue: ৳12 lakh\nWaste reduction: 65%",
                'is_featured'      => false,
                'is_hot_deal'      => true,
            ],

            // ── HealthTech (3) ────────────────────────────────────────────
            [
                'title'            => 'MediConnect',
                'sector'           => 'HealthTech',
                'stage'            => 'Series A',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => 'Patients in Bangladesh wait 3-7 days for specialist appointments. Rural patients travel 4-6 hours to see a doctor, often for conditions treatable via telemedicine.',
                'solution'         => 'MediConnect is a telemedicine platform connecting patients with 500+ verified doctors for video consultations within 30 minutes, 24/7.',
                'target_market'    => '170 million Bangladeshis with limited access to quality healthcare. Focus on urban middle class and rural populations.',
                'traction'         => '85,000 consultations completed. 500 verified doctors. ৳35 lakh monthly revenue. 4.7/5 patient rating.',
                'ask_amount'       => 25000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Doctor network expansion (35%), Marketing (30%), Technology (25%), Operations (10%)',
                'key_metrics'      => "Total consultations: 85,000\nActive doctors: 500\nMonthly revenue: ৳35 lakh\nPatient rating: 4.7/5",
                'is_featured'      => true,
                'is_hot_deal'      => false,
            ],
            [
                'title'            => 'PharmaBD',
                'sector'           => 'HealthTech',
                'stage'            => 'Seed',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => '35% of medicines sold in Bangladesh are counterfeit or substandard. Patients have no easy way to verify authenticity before purchase.',
                'solution'         => 'PharmaBD is an online pharmacy with blockchain-verified supply chain. Every medicine has a scannable QR code linking to its full provenance.',
                'target_market'    => 'Urban consumers buying prescription and OTC medicines. Initial focus on Dhaka, Chittagong, and Sylhet.',
                'traction'         => '12,000 monthly orders. ৳28 lakh GMV/month. 98.5% authentic medicine guarantee. 3 warehouse locations.',
                'ask_amount'       => 10000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Inventory expansion (45%), Delivery network (30%), Technology (25%)',
                'key_metrics'      => "Monthly orders: 12,000\nGMV: ৳28 lakh/month\nAuthenticity rate: 98.5%\nWarehouse locations: 3",
                'is_featured'      => false,
                'is_hot_deal'      => false,
            ],
            [
                'title'            => 'NutriMom',
                'sector'           => 'HealthTech',
                'stage'            => 'Pre-Seed',
                'location'         => 'Sylhet',
                'country'          => 'Bangladesh',
                'business_problem' => 'Bangladesh has one of the highest rates of child malnutrition in Asia. Mothers lack personalized, accessible guidance on infant and maternal nutrition.',
                'solution'         => 'NutriMom provides AI-powered personalized nutrition plans for pregnant women and mothers of children under 5, delivered via WhatsApp and a simple app.',
                'target_market'    => '3.5 million pregnant women and 12 million mothers of children under 5 in Bangladesh.',
                'traction'         => '2,800 active users. 89% report improved feeding practices. Partnership with 15 community health clinics.',
                'ask_amount'       => 2500000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Content & AI development (40%), Community health partnerships (35%), Marketing (25%)',
                'key_metrics'      => "Active users: 2,800\nImproved feeding practices: 89%\nClinic partners: 15\nMonthly active rate: 74%",
                'is_featured'      => false,
                'is_hot_deal'      => false,
            ],

            // ── EdTech (3) ────────────────────────────────────────────────
            [
                'title'            => 'SkillBridge BD',
                'sector'           => 'EdTech',
                'stage'            => 'Seed',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => '2 million Bangladeshi youth enter the job market annually but 60% lack industry-relevant skills. Traditional education doesn\'t bridge the gap between academia and employment.',
                'solution'         => 'SkillBridge BD offers 3-6 month job-ready bootcamps in tech, digital marketing, and finance — with a job placement guarantee or full refund.',
                'target_market'    => 'University graduates and young professionals aged 18-30 seeking career advancement. Secondary market: corporate upskilling.',
                'traction'         => '1,800 graduates. 84% placement rate within 90 days. ৳22 lakh monthly revenue. NPS: 68.',
                'ask_amount'       => 7000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Curriculum development (30%), Instructor hiring (35%), Marketing (25%), Operations (10%)',
                'key_metrics'      => "Total graduates: 1,800\nPlacement rate: 84%\nMonthly revenue: ৳22 lakh\nNPS: 68",
                'is_featured'      => true,
                'is_hot_deal'      => false,
            ],
            [
                'title'            => 'KidsLearn',
                'sector'           => 'EdTech',
                'stage'            => 'Pre-Seed',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => 'Primary school children in Bangladesh struggle with foundational literacy and numeracy. Parents lack affordable, engaging tools to support learning at home.',
                'solution'         => 'KidsLearn is a gamified learning app for children aged 5-12, covering Bangla, English, and Math through interactive stories and games aligned with the national curriculum.',
                'target_market'    => '20 million primary school children in Bangladesh. Freemium model targeting urban middle-class families.',
                'traction'         => '45,000 downloads. 8,200 paid subscribers. ৳6.5 lakh MRR. Average session: 22 minutes.',
                'ask_amount'       => 3500000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Content creation (45%), App development (30%), Marketing (25%)',
                'key_metrics'      => "Downloads: 45,000\nPaid subscribers: 8,200\nMRR: ৳6.5 lakh\nAvg session: 22 min",
                'is_featured'      => false,
                'is_hot_deal'      => false,
            ],
            [
                'title'            => 'TeacherHub',
                'sector'           => 'EdTech',
                'stage'            => 'Seed',
                'location'         => 'Chittagong',
                'country'          => 'Bangladesh',
                'business_problem' => 'Quality private tutors are inaccessible to students outside major cities. Parents spend hours finding and vetting tutors with no quality guarantee.',
                'solution'         => 'TeacherHub is a marketplace connecting verified, background-checked tutors with students for both online and in-person sessions.',
                'target_market'    => '5 million students seeking private tutoring in Bangladesh. Starting with Dhaka and Chittagong.',
                'traction'         => '3,200 verified tutors. 18,000 sessions booked. ৳14 lakh GMV/month. Tutor retention: 91%.',
                'ask_amount'       => 5500000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Tutor acquisition (40%), Platform development (35%), Marketing (25%)',
                'key_metrics'      => "Verified tutors: 3,200\nSessions booked: 18,000\nGMV: ৳14 lakh/month\nTutor retention: 91%",
                'is_featured'      => false,
                'is_hot_deal'      => true,
            ],

            // ── CleanTech (3) ─────────────────────────────────────────────
            [
                'title'            => 'SolarGrid BD',
                'sector'           => 'CleanTech',
                'stage'            => 'Series A',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => '30 million Bangladeshis still lack reliable electricity. Diesel generators cost 5x more than grid power and produce significant carbon emissions.',
                'solution'         => 'SolarGrid BD installs and operates community solar microgrids in off-grid areas, providing 24/7 clean electricity on a pay-as-you-go model via mobile payment.',
                'target_market'    => 'Off-grid communities in coastal and char areas. 8,000+ villages without reliable grid access.',
                'traction'         => '45 microgrids operational. 12,000 households connected. ৳40 lakh monthly revenue. Carbon credits: 1,200 tonnes/year.',
                'ask_amount'       => 30000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Microgrid installation (60%), Operations & maintenance (25%), Technology (15%)',
                'key_metrics'      => "Microgrids: 45\nHouseholds: 12,000\nMonthly revenue: ৳40 lakh\nCarbon credits: 1,200 t/yr",
                'is_featured'      => true,
                'is_hot_deal'      => true,
            ],
            [
                'title'            => 'WasteWise',
                'sector'           => 'CleanTech',
                'stage'            => 'Seed',
                'location'         => 'Dhaka',
                'country'          => 'Bangladesh',
                'business_problem' => 'Dhaka generates 6,500 tonnes of waste daily but only 55% is collected. Informal waste pickers lack tools to optimize routes and connect with recyclers.',
                'solution'         => 'WasteWise is a platform connecting households, waste collectors, and recyclers. AI-optimized collection routes reduce costs by 40% while increasing recycling rates.',
                'target_market'    => 'City corporations in Bangladesh\'s 12 major cities. Secondary: corporate waste management contracts.',
                'traction'         => 'Pilot in 3 Dhaka wards. 15,000 households registered. 120 waste collectors onboarded. Recycling rate up 55%.',
                'ask_amount'       => 6000000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Platform development (35%), Collector onboarding (30%), City partnerships (35%)',
                'key_metrics'      => "Households: 15,000\nCollectors: 120\nRecycling rate increase: 55%\nCost reduction: 40%",
                'is_featured'      => false,
                'is_hot_deal'      => false,
            ],
            [
                'title'            => 'AquaPure',
                'sector'           => 'CleanTech',
                'stage'            => 'Pre-Seed',
                'location'         => 'Khulna',
                'country'          => 'Bangladesh',
                'business_problem' => '20 million people in coastal Bangladesh drink arsenic-contaminated water. Existing filtration solutions are too expensive or require electricity unavailable in these areas.',
                'solution'         => 'AquaPure manufactures low-cost, solar-powered water purification units using locally-sourced materials. Each unit serves 50 families and costs 80% less than alternatives.',
                'target_market'    => 'Coastal and arsenic-affected districts: Khulna, Satkhira, Bagerhat, Jessore. 4 million households.',
                'traction'         => '85 units deployed. 4,200 families served. ৳3.2 lakh monthly revenue from subscription model.',
                'ask_amount'       => 4500000,
                'ask_currency'     => 'BDT',
                'use_of_funds'     => 'Manufacturing scale-up (50%), Distribution network (30%), R&D (20%)',
                'key_metrics'      => "Units deployed: 85\nFamilies served: 4,200\nMonthly revenue: ৳3.2 lakh\nCost vs alternatives: -80%",
                'is_featured'      => false,
                'is_hot_deal'      => false,
            ],
        ];

        // Get or create a seeker user
        $user = User::firstOrCreate(
            ['email' => 'startups@venturematch.com'],
            [
                'name'              => 'VentureMatch Startups',
                'password'          => Hash::make('password'),
                'status'            => 'active',
                'email_verified_at' => now(),
            ]
        );

        foreach ($startups as $data) {
            Opportunity::firstOrCreate(
                ['title' => $data['title']],
                array_merge($data, [
                    'user_id' => $user->id,
                    'status'  => 'approved',
                ])
            );
        }
    }
}
